"""add prompt deployment

Revision ID: 3499f5aaa443
Revises: 8d99a3dd7b0e
Create Date: 2026-05-06 20:54:50.727150

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3499f5aaa443'
down_revision: Union[str, Sequence[str], None] = '8d99a3dd7b0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prompts', sa.Column('production_version_id', sa.String(), nullable=True))
    op.add_column('prompts', sa.Column('staging_version_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'prompts', 'prompt_versions', ['production_version_id'], ['id'])
    op.create_foreign_key(None, 'prompts', 'prompt_versions', ['staging_version_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'prompts', type_='foreignkey')
    op.drop_constraint(None, 'prompts', type_='foreignkey')
    op.drop_column('prompts', 'staging_version_id')
    op.drop_column('prompts', 'production_version_id')
    # ### end Alembic commands ###
