"""add token and cost tracking

Revision ID: 583203bd43a5
Revises: 9ac4cb6ffadd
Create Date: 2026-04-30 23:06:27.176135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '583203bd43a5'
down_revision: Union[str, Sequence[str], None] = '9ac4cb6ffadd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('runs', sa.Column('tokens_used', sa.Integer(), nullable=True))
    op.add_column('runs', sa.Column('cost', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('runs', 'cost')
    op.drop_column('runs', 'tokens_used')
    # ### end Alembic commands ###
