"""add best prompt version tracking

Revision ID: 5ac8e76dfd90
Revises: a1b2c3d4e5f6
Create Date: 2026-05-02 16:16:42.265284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ac8e76dfd90'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('experiments', sa.Column('best_prompt_version_id', sa.String(), nullable=True))
    op.drop_constraint(op.f('runs_experiment_id_fkey'), 'runs', type_='foreignkey')
    op.create_foreign_key(None, 'runs', 'experiments', ['experiment_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'runs', type_='foreignkey')
    op.create_foreign_key(op.f('runs_experiment_id_fkey'), 'runs', 'experiments', ['experiment_id'], ['id'], ondelete='CASCADE')
    op.drop_column('experiments', 'best_prompt_version_id')
    # ### end Alembic commands ###
