"""support multiple prompt versions for AB testing

Revision ID: 6e98ec2ccb5b
Revises: 583203bd43a5
Create Date: 2026-05-01 09:49:58.267246

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6e98ec2ccb5b'
down_revision: Union[str, Sequence[str], None] = '583203bd43a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('experiments', sa.Column('prompt_version_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('experiments', 'prompt_version_ids')
    # ### end Alembic commands ###
