"""add user ownership

Revision ID: 8d99a3dd7b0e
Revises: c95471d87108
Create Date: 2026-05-02 20:09:19.709250

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d99a3dd7b0e'
down_revision: Union[str, Sequence[str], None] = 'c95471d87108'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('datasets', sa.Column('user_id', sa.String(), nullable=False))
    op.create_foreign_key(None, 'datasets', 'users', ['user_id'], ['id'])
    op.add_column('experiments', sa.Column('user_id', sa.String(), nullable=False))
    op.create_foreign_key(None, 'experiments', 'users', ['user_id'], ['id'])
    op.add_column('prompts', sa.Column('user_id', sa.String(), nullable=False))
    op.create_foreign_key(None, 'prompts', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'prompts', type_='foreignkey')
    op.drop_column('prompts', 'user_id')
    op.drop_constraint(None, 'experiments', type_='foreignkey')
    op.drop_column('experiments', 'user_id')
    op.drop_constraint(None, 'datasets', type_='foreignkey')
    op.drop_column('datasets', 'user_id')
    # ### end Alembic commands ###
