"""add users table

Revision ID: c95471d87108
Revises: 5ac8e76dfd90
Create Date: 2026-05-02 19:23:18.749470

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c95471d87108'
down_revision: Union[str, Sequence[str], None] = '5ac8e76dfd90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.drop_constraint(op.f('prompt_versions_prompt_id_fkey'), 'prompt_versions', type_='foreignkey')
    op.create_foreign_key(None, 'prompt_versions', 'prompts', ['prompt_id'], ['id'])
    op.drop_constraint(op.f('runs_experiment_id_fkey'), 'runs', type_='foreignkey')
    op.create_foreign_key(None, 'runs', 'experiments', ['experiment_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'runs', type_='foreignkey')
    op.create_foreign_key(op.f('runs_experiment_id_fkey'), 'runs', 'experiments', ['experiment_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'prompt_versions', type_='foreignkey')
    op.create_foreign_key(op.f('prompt_versions_prompt_id_fkey'), 'prompt_versions', 'prompts', ['prompt_id'], ['id'], ondelete='CASCADE')
    op.drop_table('users')
    # ### end Alembic commands ###
