"""add projects and workspace system

Revision ID: dbaf86562637
Revises: 3499f5aaa443
Create Date: 2026-05-06 22:23:25.335335

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbaf86562637'
down_revision: Union[str, Sequence[str], None] = '3499f5aaa443'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('owner_user_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('playground_runs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_members',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('datasets', sa.Column('project_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'datasets', 'projects', ['project_id'], ['id'])
    op.add_column('experiments', sa.Column('project_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'experiments', 'projects', ['project_id'], ['id'])
    op.add_column('prompts', sa.Column('project_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'prompts', 'projects', ['project_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'prompts', type_='foreignkey')
    op.drop_column('prompts', 'project_id')
    op.drop_constraint(None, 'experiments', type_='foreignkey')
    op.drop_column('experiments', 'project_id')
    op.drop_constraint(None, 'datasets', type_='foreignkey')
    op.drop_column('datasets', 'project_id')
    op.drop_table('project_members')
    op.drop_table('playground_runs')
    op.drop_table('projects')
    # ### end Alembic commands ###
